//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTU.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IRealTimeUnit")]
    public interface IRealTimeUnit {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnit/Init", ReplyAction="http://tempuri.org/IRealTimeUnit/InitResponse")]
        bool Init(string id, string address, byte[] signature, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnit/Init", ReplyAction="http://tempuri.org/IRealTimeUnit/InitResponse")]
        System.Threading.Tasks.Task<bool> InitAsync(string id, string address, byte[] signature, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnit/UpdateValue", ReplyAction="http://tempuri.org/IRealTimeUnit/UpdateValueResponse")]
        void UpdateValue(string address, int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRealTimeUnit/UpdateValue", ReplyAction="http://tempuri.org/IRealTimeUnit/UpdateValueResponse")]
        System.Threading.Tasks.Task UpdateValueAsync(string address, int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRealTimeUnitChannel : RTU.ServiceReference.IRealTimeUnit, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RealTimeUnitClient : System.ServiceModel.ClientBase<RTU.ServiceReference.IRealTimeUnit>, RTU.ServiceReference.IRealTimeUnit {
        
        public RealTimeUnitClient() {
        }
        
        public RealTimeUnitClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RealTimeUnitClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeUnitClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RealTimeUnitClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Init(string id, string address, byte[] signature, string message) {
            return base.Channel.Init(id, address, signature, message);
        }
        
        public System.Threading.Tasks.Task<bool> InitAsync(string id, string address, byte[] signature, string message) {
            return base.Channel.InitAsync(id, address, signature, message);
        }
        
        public void UpdateValue(string address, int value) {
            base.Channel.UpdateValue(address, value);
        }
        
        public System.Threading.Tasks.Task UpdateValueAsync(string address, int value) {
            return base.Channel.UpdateValueAsync(address, value);
        }
    }
}
